### ISSUE TITLE
failed to select a version for `futures`

### ISSUE THREAD

**Issue by dmarti** [sdleffler/attaca#10]
Error on install ( 960b5f587ef33fb7e10d338e354ff4d61f25dd77 )

```
[attaca](master)$ cargo install
  Installing attaca v0.1.0 (file:///home/dmarti/Projects/attaca)
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/alexcrichton/futures-await`
    Updating git repository `https://github.com/sdleffler/indicatif`
    Updating git repository `https://github.com/sdleffler/owning-ref-rs`
    Updating git repository `https://github.com/dtolnay/syn`
    Updating git repository `https://github.com/dtolnay/quote`
error: failed to compile `attaca v0.1.0 (file:///home/dmarti/Projects/attaca)`, intermediate artifacts can be found at `/home/dmarti/Projects/attaca/target`

Caused by:
  failed to select a version for `futures` (required by `rad`):
all possible versions conflict with previously selected versions of `futures`
  version 0.1.14 in use by futures v0.1.14
  possible versions to select: 0.1.16
[attaca](master)$ cargo --version
cargo 0.23.0-nightly (e447ac7e9 2017-09-27)
```

**Comment by sdleffler** [comment]
I'm unable to reproduce this. Could you try running `cargo clean` and then `cargo build` again?

**Comment by dmarti** [comment]
```
[attaca](master)$ cargo clean
[attaca](master)$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/alexcrichton/futures-await`
    Updating git repository `https://github.com/sdleffler/owning-ref-rs`
    Updating git repository `https://github.com/sdleffler/indicatif`
error: failed to select a version for `futures` (required by `futures-bufio`):
all possible versions conflict with previously selected versions of `futures`
  version 0.1.16 in use by futures v0.1.16
  possible versions to select: 0.1.14
```

**Comment by sdleffler** [comment]
Can you remove your `Cargo.lock` file and try again?

**Comment by dmarti** [comment]
This worked after I did `cargo update`.

**Comment by dmarti** [comment]
Does there need to be a  `cargo update` step in the README?

**Comment by sdleffler** [comment]
There shouldn't need to be, at least not as a standard step as part of installation. This happened because I needed to update dependencies, so it'll only happen if someone `git pull`s a new version of the source (after previously compiling the project) and the `Cargo.toml` has, say, changed the version of `futures` it uses and simultaneously added new crates dependent on the new version. Within the next couple of commits I will actually begin tracking my `Cargo.lock` file, which will prevent this problem from happening again (since the build, as far as the Rust crates involved, will be identical to whatever builds on my machine, and doing a `git pull` will essentially update it for you.) This is actually the recommended option, which I forgot about when I originally `cargo new`'d the project. :P
